[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:web]
command=uvicorn immigration_algoflow_APIs.asgi:application --host 0.0.0.0 --port 8098
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:celery]
command=celery -A immigration_algoflow_APIs worker --loglevel=INFO --queues=file_reading,extraction,ocr,indexing,generation,verification,conversion,webhooks --max-tasks-per-child=25
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
